version: '3.9'

services:
  db:
    image: postgres:15.2
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 6432:5432
  web:
    build:
      context: .
    # image: image name with version
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
    depends_on:
      - db
    ports:
      - 8000:8000

volumes:
  postgres_data:
